--DROP TABLE [Utilisateur]

--CREATE TABLE `Sassan_neuro_compte_Admin` (
--  `id` int UNSIGNED NOT NULL,
--  `nom` longtext NOT NULL,
--  `email` varchar(80) NOT NULL,
--  `mdp` varchar(32) DEFAULT NULL,
--  `activate` int NOT NULL DEFAULT '0',
--  `admin` int NOT NULL DEFAULT '0',
--  `valider` int NOT NULL DEFAULT '0',
--  `created` datetime NOT NULL,
--  `hash` varchar(32) NOT NULL
--) ENGINE=MyISAM DEFAULT CHARSET=utf8;